#!/usr/bin/perl

require "libswxrt.pl";
use File::Copy;

our %Task = (
	name    => 'findRMF',
	version => '0.1',
	releasedate => "2016-03-13",
	chatter => 2,
	status => 0,
	errmess => '',
	stem    => '',
	author  => 'Y.Wang',
    );

		
# Initial 

my $isCopy = 0; # 0 is no, 1 is yes.

# Main #

## read parameter
my $filename = $ARGV[0] if ($ARGV[0]);

unless(defined $filename){
print "Please input the FITS filename (eg. sw00271019000xwtw2po_cl.evt):\n";
chomp($filename = <STDIN>);
}


## get response matrix file 
my $rmfFilename = &GetRmfFile($filename);

## copy rmf file to current folder
$copied = copy($rmfFilename, "./") if $rmfFilename and $isCopy;
print "\nRMF file has been copied to current folder.\n" if $copied;
print "Cannot find corresponding RMF file. \n" unless $rmfFilename;