#!/usr/bin/perl

require "libswxrt.pl";
use File::Copy;

# Task info

our %Task = (
    name        => 'findRMF',
    version     => '0.2',
    releasedate => "2016-03-13",
    chatter     => 2,
    status      => 0,
    errmess     => '',
    stem        => '',
    author      => 'Y.Wang',
);

# Initial

my $isCopy = 0;    # 0 is no, 1 is yes.

# Main #

return 0 if $Task{status};

## read parameter
my $filename = $ARGV[0] if ( $ARGV[0] );

unless ( defined $filename ) {
    &PrntChty( 1, "Please input the FITS filename (eg. sw00271019000xwtw2po_cl.evt):\n" );
    chomp( $filename = <STDIN> );
}

## get response matrix file
&GetRmfFile($filename);

&Error if $Task{status};

## copy rmf file to current folder
$copied = copy( $rmfFilename, "./" ) if $rmfFilename and $isCopy;
&PrntChty( 2, "\nRMF file has been copied to current folder.\n" ) if $copied;
